"""MILAN template mapping: 175 fields, in canonical Master Mapping order.

Mirrors r_reference/R/milan_mapping.R. Implementation lands in Stage 9; for
now this module exposes the canonical column list and code-map dictionaries
so the parity harness can reference them.
"""

from __future__ import annotations

# Canonical 175-column output order. Copied verbatim from
# r_reference/R/milan_mapping.R:199-304. Do not reorder; downstream parity
# tests depend on this exact sequence.
MILAN_EXPECTED_OUTPUT_COLS: tuple[str, ...] = (
    "Originator Identifier", "Servicer Identifier",
    "Borrower Identifier", "Property Identifier", "Loan Identifier",
    "Loan Currency", "Loan OB", "Loan CB",
    "Origination Date", "Maturity Date",
    "Origination Channel", "Loan Purpose",
    "Principal Payment Frequency", "Interest Payment Frequency",
    "Principal Payment Type", "Periodic Payment",
    "Ranking", "Total Prior Ranks CB", "Total Prior Ranks OB",
    "External Prior Ranks CB", "Pari Passu Ranking Loans (Not In Pool)",
    "Retained Amount", "Further Advances", "Flexible Loan Amount",
    "Grace Period", "Type of Payment Holiday",
    "Length of Payment Holiday Allowed In Months",
    "Interest Rate Type", "Base Index",
    "Interest Rate", "Full Margin", "Margin After Reset Date",
    "Interest Reset Date",
    "Months Current", "Arrears Amount", "Months In Arrears",
    "Number of Payments Before Securitisation",
    "Social Programme Type",
    "FX Risk Mitigated", "Inflation-Indexed Loan",
    "Exchange Rate At Loan Origination",
    "Borrower Type", "Borrower Residency", "Borrower Birth Year",
    "Employment Type", "Internal Credit Score", "Credit Score - Canada",
    "Borrower Postal/Zip Code", "Number of Borrowers",
    "Income Borrower 1", "Income Verification For Primary Income",
    "Income Borrower 2", "Income Verification For Secondary Income",
    "Guarantor's Income", "Total Income", "DTI Ratio",
    "Loan To Employee", "Number of Properties Owned By Borrower",
    "Regulated",
    "Prior Missed On Previous Mortgage",
    "Live Units of Adverse Credit", "Satisfied Units of Adverse Credit",
    "Total Amount of CCJs or Balance of Adverse Credit",
    "Number of Other Adverse Credit Events",
    "Prior Personally Bankruptcy Or IVA",
    "Prior Repossessions On Previous Mortgage", "Prior Litigation",
    "Deposit Amount", "Property Type", "Property Value", "Purchase Price",
    "Recourse", "Property Valuation Type", "Property Valuation Date",
    "Confidence Interval For Original AVM Valuation",
    "Provider of Original AVM Valuation",
    "Property Postal, Region code or Nuts code",
    "Occupancy Type", "Rental Income", "Metro / Non Metro",
    "Construction Year",
    "Mortgage Inscription - Property 1", "Mortgage Mandate - Property 1",
    "Property Identifier Property 2", "Property Type - Property 2",
    "Property Value Property 2", "Property Valuation Type - Property 2",
    "Property Valuation date Property 2", "Property Postcode Property 2",
    "Occupancy Type - Property 2",
    "Mortgage Inscription Property 2", "Mortgage mandate Property 2",
    "Property Identifier Property 3", "Property Type - Property 3",
    "Property Value Property 3", "Property Valuation Type - Property 3",
    "Property Valuation date Property 3", "Property Postcode Property 3",
    "Occupancy Type - Property 3",
    "Mortgage Inscription Property 3", "Mortgage mandate Property 3",
    "Property Identifier Property 4", "Property Type - Property 4",
    "Property Value Property 4", "Property Valuation Type - Property 4",
    "Property Valuation date Property 4", "Property Postcode Property 4",
    "Occupancy Type - Property 4",
    "Mortgage Inscription Property 4", "Mortgage mandate Property 4",
    "Property Identifier Property 5", "Property Type - Property 5",
    "Property Value Property 5", "Property Valuation Type - Property 5",
    "Property Valuation date Property 5", "Property Postcode Property 5",
    "Occupancy Type - Property 5",
    "Mortgage Inscription Property 5", "Mortgage mandate Property 5",
    "Original LTV", "Current LTV",
    "Energy Performance Certificate Value",
    "Energy Performance Certificate Provider Name",
    "Additional Collateral Type", "Additional Collateral Provider",
    "Additional Collateral Value",
    "Account Status", "Repurchase Date",
    "Restructured Loan", "Restructuring Date", "Restructuring Type",
    "Redemption Date",
    "Default amount", "Default date",
    "Reason for Default or Foreclosure",
    "Allocated Losses", "Cumulative Recoveries", "Sale Price",
    "MIG Provider", "Type of Guarantee Provider",
    "MIG %", "Initial MCI Coverage Amount", "Current MCI Coverage Amount",
    "Additional data 1 - calc_loan_id",
    "Additional data 2 - calc_borrower_id",
    "Additional data 3 - calc_main_property_id",
    "Additional data 4 - calc_collateral_group_id",
    "Additional data 5 - calc_nr_loans_in_group",
    "Additional data 6 - calc_nr_properties_in_group",
    "Additional data 7 - calc_full_set",
    "Additional data 8 - calc_cross_collateralized_set",
    "Additional data 9 - calc_structure_type",
    "Additional data 10 - calc_aggregated_property_value",
    "Additional data 11 - calc_original_LTV",
    "Additional data 12 - calc_current_LTV",
    "Additional data 13 - calc_seasoning",
    "Additional data 14 - lien",
    "Additional data 15 - prior_principal_balances",
    "Additional data 16 - pari_passu_underlying_exposures",
    "Additional data 17 - original_valuation_method",
    "Additional data 18 - original_valuation_date",
    "Additional data 19 - current_valuation_method",
    "Additional data 20 - current_valuation_date",
    "Additional data 21 - new_underlying_exposure_identifier",
    "Additional data 22 - original_underlying_exposure_identifier",
    "Additional data 23 - new_obligor_identifier",
    "Additional data 24 - original_obligor_identifier",
    "Additional data 25 - new_collateral_identifier",
    "Additional data 26 - original_collateral_identifier",
    "column for additional data 27", "column for additional data 28",
    "column for additional data 29", "column for additional data 30",
    "column for additional data 31", "column for additional data 32",
)

assert len(MILAN_EXPECTED_OUTPUT_COLS) == 175, (
    f"MILAN_EXPECTED_OUTPUT_COLS must have 175 entries, has {len(MILAN_EXPECTED_OUTPUT_COLS)}"
)
